version: '3.9'

services:
  db:
    image: postgres
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

# volumes:
#   postgres_data:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - 3000:3000

    volumes:
      - ./frontend:/app/frontend

    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - 8000:8000

    depends_on:
      - db

